apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keygrav
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-php-grav
    spec:
      containers:
      - name: keygrav
        image: setevoy/keygrav:3
        ports:
        - containerPort: 80
